language: java
jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_deploy:
  - export RELEASE_FILE=$(ls ./build/libs/*.jar)

deploy:
  provider: releases
  api_key:
    secure: pZx6oJWfKoOX8R2YPIRZx03+ME44PWMZ1S6VawiFgLE8HUFT+dfOkBODOSRazWRNTA/Avb2BgXTuX1GWwbUaJ1JefpGmLW18ehnTIsn1fTG33vtK2ovseTfmI/wHQTssEJlzZASMtRoLXeS413m+F47PzPSugAGoxhFufY7AZHi9401f8/0jDxenUTDRYOL193SuVfI1i5cruGw0xH5EFq6vDicZGzHcAQEeD1b2bxFG1x4PSfrDSNxWhANPI8rSWmVqiDrXpqLMLWkns0iyEswyi5SHC1gy3rGwCHV0AzinkahnFZAhclhlBWZwyMaAagMdSrzmIQmmLjBFgvjkaMdX0PLrPFp2MUi60dcScqKvlp3ERQ4zvk9+/6XqDNtB30ESz7Eqyw+EkGtVip1y6rFKpVHxnT18cnCtRVHBvTC5GsvJ/ed1xey1otIpwnaf6R1HtIdcvejjhTdqfG9ZHjhFF7ioN1X4dZv3EK3exZBJHQRlVlxS+EHEXakwOIV7hwk3EtaLV4CIg9aHFJ6YC6SCM4ifLvzwJdewlSdSEqHmGMAHNMZZAfV+YyCPM9ylsxCMO3TOR28J7oYnRJ9QPZ0C/ZWhEEF235OprBXs2rIYkixn7L5zZ18GPZ0zgKcqGZbY7clSUI8XmwSoOxFJS61cG65wpHPh5aYuaPopq8o=
  file_glob: true
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true